import type { Metadata } from "next";
import { Trirong } from "next/font/google";
import "./globals.css";

const trirong = Trirong({ subsets: ["latin"] , weight: ["300", "400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={trirong.className}>
      <body className="py-16">{children}</body>
    </html>
  );
}
